/*
 *
 * Generated by VERN
 *
 */

'use strict';

angular.module('{{appName}}', ['ngSanitize', 'ngRoute', 'LocalStorageModule', 'ui.bootstrap', '{{appName}}.filters', 'ngDictionary', 'vernAngularStandard'])
  .config(['$httpProvider', function($httpProvider) {
    $httpProvider.defaults.useXDomain = true;
    delete $httpProvider.defaults.headers.common['X-Requested-With'];
  }]);
