/*
 *
 * Generated by VERN
 *
 */

'use strict';

angular.module('{{adminAppName}}', ['ngSanitize', 'ngRoute', 'LocalStorageModule', 'ui.bootstrap', 'ui.sortable', '{{adminAppName}}.filters', 'ngDictionary', 'vernAngularStandard', 'vernAngularAdmin'])
  .config(['$httpProvider', function($httpProvider) {
    $httpProvider.defaults.useXDomain = true;
    delete $httpProvider.defaults.headers.common['X-Requested-With'];
  }]);
