/*
 *
 * Generated by VERN
 *
 */

'use strict';

var app = angular.module('{{adminAppName}}').config(function ($routeProvider, $locationProvider, vernConfigProvider, $httpProvider) {
  for(var j in vernConfigProvider.routes) {
    for(var i = 0; i < vernConfigProvider.routes[j].length; i++) {
      var r = vernConfigProvider.routes[j][i];
      $routeProvider.when(r.path, {
        templateUrl: r.templateUrl,
        innerTemplateUrl: r.innerTemplateUrl,
        controller: r.controller,
        event: r.event,
        section: r.section,
        page_title: r.page_title
      });
    }
  }
  $routeProvider.otherwise({
    redirectTo: '/'
  });
  $httpProvider.interceptors.push(function($q) {
    return {
      'requestError': function(rejection) {
        return $q.reject(rejection);
      },
      'responseError': function(rejection) {
        // may want to do something here to handle bad views
        return $q.reject(rejection);
      }
    }
  });
  $locationProvider.hashPrefix('!');
});
