/**
 *  {{appName}} AngularJS Vern Module
 *
 *  Generated by Vern
 *
 */

'use strict';

angular.module('{{appName}}', []);
//$templateCache
angular.module('{{appName}}')
  /*
  .constant('{{appName}}Config', {

  })
  .directive('{{appName}}Directive', function() {

  })
  .controller('{{appName}}Controller', function() {

  })
  .service('{{appName}}Service', function() {

  })
  .factory('{{appName}}Factory', function() {

  })
  .provider('{{appName}}Provider', function() {

  })
  .filter('{{appName}}Filter', function() {

  })
  */;