/*
 *
 * Generated by VERN
 *
 */
'use strict';

angular.module('{{appName}}')
  .directive('{{directive_name}}', function() {
    return { {{#scope}}
      {{scope}}
      {{/scope}}restrict: '{{restrictions}}',{{#templateCache}}
      templateUrl: function(tElement, tAttrs) {
        var url = '{{template_url}}';
        if(tAttrs.templateUrl) {
          url = tAttrs.templateUrl;
        }

        return url;
      },{{/templateCache}}{{#controller}}
      controller: function($scope, $element, $attrs) {

      },{{/controller}}
      link: function(scope, element, attrs) {

      }
    }
  });

{{#templateCache}}
angular.module('{{appName}}').run(['$templateCache', function($templateCache) {
  $templateCache.put('{{template_url}}',
      '<div class="{{name}}">' +
      '</div>'
  );
}]);

{{/templateCache}}