/*
 *
 * Generated by VERN
 *
 */
function Model($vern) {
  function IndexModel() {
    this.name = null;
    this.tags = [];
    this.post = null;

    return this.update(arguments[0]);
  }

  new $vern.model().extend(IndexModel, {
    collection: 'test',
    validations: {
      name: 'notEmpty',
      tags: function(val, data) {
        if(!(val instanceof Array)) {
          return new Error('Tags should be an array');
        }

        return val;
      }
    },
    indexes: ['name'],
    exclude: [],
    validation_exceptions: {},
    non_editable: []
  });

  return IndexModel;
}

module.exports = Model;