/*
 *
 * Generated by VERN
 *
 */
var validator = require('validator');

module.exports = function Model(scope) {
  function TagCloudModel() {
    this.type = null;
    this.name = null;
    this.value = null;

    return this.update(arguments[0]);
  }

  new scope.model().extend(TagCloudModel, {
    collection: 'tag-cloud',
    indexes: ['value'],
    validations: {
      type: 'notEmpty',
      name: 'notEmpty'
    }
  });

  return TagCloudModel;
};