/*
 *
 * Generated by VERN
 *
 */
'use strict';

angular.module('{{appName}}.filters', [])
  .filter('{{filter_name}}', function() {
    return function(input, options) {
      var out = '';

      return out;
    }
  });