/*
 *
 * Generated by VERN
 *
 * {{controller_name}}
 *
 * Description of {{controller_name}}
 *
 */
'use strict';

angular.module('{{appName}}')
  .controller('{{controller_name}}', function($scope) {
    $scope.data = {};
  });