/*
 *
 * Generated by VERN
 *
 */
'use strict';

angular.module('{{appName}}')
  .provider('{{service_name}}', function () {
    this.$get = function() {
      return {
        hello: function() {
          
        }
      };
    };
  });