/*
 *
 * Generated by VERN
 *
 */
'use strict';

angular.module('{{appName}}')
  .service('{{service_name}}', function () {
    function {{service_name}}() {

    }

    return new {{service_name}}();
  });