/**
 * Generated by VERN
 *
 * Description for TagCloudController
 *
 * @class TagCloudController
 * @constructor
 */
function TagCloudController($vern) {
  var validator      = require('validator');

  var $scope = new $vern.controller(TagCloudController);
  $scope.model = $vern.models.TagCloudModel;

  $scope.routeDefaults.requiresGroup = true;

  $scope.beforePost(function(data, callback) {
    data.object.value = data.object.name.toLowerCase();
    var q = {type: data.object.type, value: data.object.value};
    if(data.req.group) {
      q._groups = data.req.group._id.toString
    }
    new $vern.models.TagCloudModel().query(q, function(err, tags) {
      if(tags.length) {
        data.object._id = tags[0]._id;
        return callback(null, data);
      }

      callback(null, data);
    });
  });

  return $scope;
}

module.exports = TagCloudController;